object Versions {

    // Gradle plugins
    const val androidGradlePlugin = "4.1.3"
    const val kotlinGradlePlugin = "1.6.10"
    const val googleServicesGradlePlugin = "4.3.10"
    const val crashlyticsGradlePlugin = "2.8.1"

    // Normal Dependencies
    const val hilt = "2.38.1"
    const val navigation = "2.3.5"
    const val kotlin = "1.5.10"
    const val ktor = "2.1.0"
    const val timber = "4.7.1"
    const val appCompat = "1.3.0"
    const val material = "1.3.0"
    const val material3 = "1.0.1"
    const val constraintLayout = "1.1.3"
    const val jUnit = "4.12"
    const val datastore = "1.0.0-alpha08"
    const val ktx = "1.8.0"
    const val legacy = "1.0.0"
    const val lifecycle = "2.3.0"
    const val lifecycleExtensions = "2.2.0"
    const val coroutines = "1.5.2"
    const val room = "2.3.0-beta03"
    const val gson = "2.8.6"
    const val coil = "1.2.1"
    const val wysiwyg = "4.0"
    const val nativeEditor = "3.0.3"
    const val richEditor = "2.0.0"
    const val prettyTime = "4.0.4.Final"
    const val delegate = "1.0.0"
    const val switch = "0.0.3@aar"
    const val circularImageView = "4.2.0"
    const val liquidSwipe = "1.0.0"
    const val playServicesAuth = "19.0.0"
    const val playCoroutines = "1.3.7"
    const val paging = "3.1.0"
    const val retrofit = "2.9.0"
    const val recyclerview = "1.2.1"
    const val recyclerviewSelection = "1.0.0"
    const val sneaker = "2.0.0"
    const val alert = "1.0.1"
    const val alerter = "7.2.4"
    const val support = "27.1.0"
    const val likeButton = "0.2.3"
    const val scrollLayout = "1.0.3"
    const val hiltWork = "1.0.0"
    const val workManager = "2.7.1"
    const val androidXStartup = "1.1.0"
    const val motionToast = "1.4"
    const val chuck = "1.1.0"

    // Bill Of Materials
    const val okHttp = "4.7.2"
    const val firebaseBOM = "29.0.4"
}